//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars
    {
        public int Id { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public string email { get; set; }

        public string cat { get; set; }
        public Nullable<int> No { get; set; }
        public string adaptation { get; set; }
        public Nullable<int> NoOfDoors { get; set; }
        public string Image { get; set; }
        public Nullable<int> priceForDay { get; set; }
        public string book { get; set; }
    }
}
