//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentRequst
    {
        public int Id { get; set; }
        public string CarId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerPhone { get; set; }
        public Nullable<int> Rentduration { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public string Occasion { get; set; }
        public string Additions { get; set; }
        public string Pay { get; set; }
        public string email { get; set; }
    }
}
